#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/alkz/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#xcompmgr -fF -I-.004 -O-.004 -D2 -cC -t-4 -l-6 -r6 &
#fbsetbg ~/images/yhalothar.png
exec xcompmgr -r10 -D5 -C -o0.8 &
setgif ~/images/hypercube.gif
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/alkz/.fluxbox/log"
